In [2]:
train_file_path = r"C:\Users\ADARSH\Desktop\Projects\Machine_learning_project\housing\artifact\data_ingestion\2022-10-11-20-37-21\ingested_data\train\housing.csv"

In [3]:
import pandas as pd


In [4]:
df = pd.read_csv(train_file_path)

In [5]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2237.0       706.0         2.1736             72100.0          INLAND  
1      2015.0       768.0         6.3373            279600.0      NEAR OCEAN  
2       667.0       300.0         2.8750             82700.0          INLAND  
3       898.0       483.0         2.2264            112500.0      NEAR OCEAN  
4      1837.0       580.0         4.4964            238300.0       <1H OCEAN

In [6]:
df.shape

(16512, 10)

In [7]:
x,y=df.drop(columns=["median_house_value"],axis=1),df[["median_house_value"]]

In [8]:
x.shape

(16512, 9)

In [9]:
y.shape

(16512, 1)

In [10]:
x

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity  
0          2237.0       706.0         2.1736          INLAND  
1          2015.0       768.0         6.3373      NEAR OCEAN  
2           667.0       300.0         2.8750          INLAND  
3           898.0       483.0         2.2264      NEAR OCEAN  
4          1837.0       580.0         4.4964       <1H OCEAN  
...           ...         ...            ...             ...  
16507      2026.0      1001.0         5.0900       <1H OCEAN  
16508      4769.0      1418.0         2.8139          INLAND  
16509       458.0       172.0         3.1797       <1H OCEAN  
16510      1208.0       501.0         4.1964       <1H OCEAN  
16511       625.0       197.0         3.1319          INLAND  

[16512 rows x 9 columns]

In [11]:
y

median_house_value
0                 72100.0
1                279600.0
2                 82700.0
3                112500.0
4                238300.0
...                   ...
16507            268500.0
16508             90400.0
16509            140400.0
16510            258100.0
16511             62700.0

[16512 rows x 1 columns]

In [12]:
x.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [13]:
#Handling NULL values
from sklearn.impute import SimpleImputer

In [14]:
numerical_column = x.drop(columns = ["ocean_proximity"],axis = 1)

In [15]:
numerical_column

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -121.46     38.52                29.0       3873.0           797.0   
1        -117.23     33.09                 7.0       5320.0           855.0   
2        -119.04     35.37                44.0       1618.0           310.0   
3        -117.13     32.75                24.0       1877.0           519.0   
4        -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
16507    -117.07     33.03                14.0       6665.0          1231.0   
16508    -121.42     38.51                15.0       7901.0          1422.0   
16509    -122.72     38.44                48.0        707.0           166.0   
16510    -122.70     38.31                14.0       3155.0           580.0   
16511    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  
0          2237.0       706.0         2.1736  
1          2015.0       768.0         6.3373  
2           667.0       300.0         2.8750  
3           898.0       483.0         2.2264  
4          1837.0       580.0         4.4964  
...           ...         ...            ...  
16507      2026.0      1001.0         5.0900  
16508      4769.0      1418.0         2.8139  
16509       458.0       172.0         3.1797  
16510      1208.0       501.0         4.1964  
16511       625.0       197.0         3.1319  

[16512 rows x 8 columns]

In [16]:
simple_imputer = SimpleImputer(strategy="median")

In [17]:
simple_imputer.fit_transform(numerical_column)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [18]:
df = simple_imputer.transform(numerical_column)

In [19]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [20]:
simple_imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [118]:
x.longitude.median()

-118.51

In [21]:
x.latitude.median()

34.26

In [22]:
#checking for the categorical columns
x.ocean_proximity.value_counts()

<1H OCEAN     7277
INLAND        5262
NEAR OCEAN    2124
NEAR BAY      1847
ISLAND           2
Name: ocean_proximity, dtype: int64

In [23]:
simple_imputer = SimpleImputer(strategy="most_frequent")
#StandardScaler
#minmaxscaler
#onehotencoder
#levelencoder

In [24]:
fit,transform and fit_transform

NameError: name 'fit' is not defined

In [ ]:
customer transformer

In [24]:
#customtransforms
#must have atleast two functions
from sklearn.base import BaseEstimator, TransformerMixin


class Test(BaseEstimator,TransformerMixin):
    def __init__(self,strategy="median"):
        self.strategy = strategy
        
    def fit(self,X):
        self.features_ = X.columns
        self.statistic_ = []
        for column in X.columns:
            self.statistic_.append(X[column].median())
        return self

    def transform(self,X:pd.DataFrame):
        for idx,column in enumerate(x.columns):
            X[column].fillna(self.statistic_[idx])
        return X   
    # def fit_transform(self,X):
    #     self.fit(X)
    #     return self.transform(X)

In [25]:
for idx,column in enumerate(x.columns):
    print(idx,column)

0 longitude
1 latitude
2 housing_median_age
3 total_rooms
4 total_bedrooms
5 population
6 households
7 median_income
8 ocean_proximity


In [26]:
response = Test().fit(numerical_column)

In [27]:
response.statistic_

[-118.51, 34.26, 29.0, 2119.0, 433.0, 1164.0, 408.0, 3.54155]

In [28]:
import numpy as np

In [29]:
x.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [30]:
from tkinter import E


COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"
COLUMN_TOTAL_BEDROOM = "total_bedrooms"

class FeatureGenerator(BaseEstimator, TransformerMixin):

    def __init__(self, add_bedrooms_per_room=True,total_rooms_ix=3,population_ix=5,households_ix=6,total_bedrooms_ix=4, columns=None):
        
                   
        """   FeatureGenerator Initialization add_bedrooms _per_room: bool total_rooms_ix: int index number of total rooms columns population_ix: int index number of total population columns households_ix: int index number of households columns total_bedrooms_ix: int index number of bedrooms columns"""
        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix = self.columns.index(COLUMN_POPULATION)
                households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix = self.columns.index(COLUMN_TOTAL_BEDROOM)
            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_rooms_ix = total_rooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            self.total_bedrooms_ix = total_bedrooms_ix

        except Exception as e:
            raise e
    def fit(self,X,y=None):
        return self

    def transform(self,X,y=None):
        try:
            room_per_household = X[:,self.total_rooms_ix]/X[:,self.households_ix]
            population_per_household = X[:self.population_ix]/X[:,self.households_ix]
            if self.add_bedrooms_per_room:
                bedrooms_per_room = X[:,self.total_bedrooms_ix]/X[:,self.total_rooms_ix]
                generated_feature = np.c_[X,room_per_household,population_per_household,bedrooms_per_room]
            else:
                generated_feature = np.c_[X,room_per_household,population_per_household]
            
            return generated_feature
        except Exception as e:
            raise e

            


In [31]:
arr1 = np.arange(10)
arr2 = np.arange(10)

In [32]:
np.c_[arr1,arr2]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [130]:
# Feature Engineering Pipeline standard way 

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
num_pipeline = Pipeline(steps = [
    ('imputer',SimpleImputer(strategy="median")),
    ('feature_generator',FeatureGenerator()),
    ('scaling',StandardScaler())
])

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [38]:
cat_pipeline = Pipeline(steps = [
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('oneHotEncoder',OneHotEncoder()),
    ('scaling',StandardScaler(with_mean=False))
])

In [39]:
df = pd.read_csv(train_file_path)

In [137]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [40]:
num_column_name = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']
cat_column_name = ['ocean_proximity']

In [41]:
preprocessing = ColumnTransformer([
    ('num_pipeline',num_pipeline,num_column_name),
    ('cat_pipeline',cat_pipeline,cat_column_name)]
)

In [44]:
preprocessing.fit_transform(df)

ValueError: operands could not be broadcast together with shapes (5,8) (16512,) 

In [141]:
test_file_path = r"C:\Users\ADARSH\Desktop\Projects\Machine_learning_project\housing\artifact\data_ingestion\2022-10-11-20-37-21\ingested_data\test\housing.csv"

In [142]:
test_df = pd.read_csv(test_file_path)

In [143]:
test_file_path

'C:\\Users\\ADARSH\\Desktop\\Projects\\Machine_learning_project\\housing\\artifact\\data_ingestion\\2022-10-11-20-37-21\\ingested_data\\test\\housing.csv'

In [144]:
test_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -118.39     34.12                29.0       6447.0          1012.0   
1    -120.42     34.89                24.0       2020.0           307.0   
2    -118.45     34.25                36.0       1453.0           270.0   
3    -118.10     33.91                35.0       1653.0           325.0   
4    -117.07     32.77                38.0       3779.0           614.0   

   population  households  median_income  median_house_value ocean_proximity  
0      2184.0       960.0         8.2816            500001.0       <1H OCEAN  
1       855.0       283.0         5.0099            162500.0       <1H OCEAN  
2       808.0       275.0         4.3839            204600.0       <1H OCEAN  
3      1072.0       301.0         3.2708            159700.0       <1H OCEAN  
4      1495.0       614.0         4.3529            184000.0      NEAR OCEAN

In [145]:
preprocessing.transform(test_df)

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

In [146]:
import dill

In [148]:
with open('preprocessing.pkl','wb') as prep_file:
    dill.dump(preprocessing,prep_file)
    

In [149]:
with open('preprocessing.pkl','rb') as file_obj:
    preprocessing_loaded_object = dill.load(file_obj)

In [150]:
preprocessing_loaded_object

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('feature_generator',
                                                  FeatureGenerator()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['longitude', 'latitude', 'housing_median_age',
                                  'total_rooms', 'total_bedrooms', 'population',
                                  'households', 'median_income']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('OneHotEncoder',
                                 

In [1]:
preprocessing_loaded_object.transform(test_df)

NameError: name 'preprocessing_loaded_object' is not defined